### ISSUE TITLE
Comment is moved unnecessarily, causing confusion

### ISSUE THREAD

**Issue by vineethk** [movebit/movefmt#1]
Consider the following code:

```
// first module
module 0xc0ffee::m {
    fun test() {}
}

// second module
module 0xc0ffee::n {
    fun test() {}
}
```

If we format the above code, we get:
```
// first module
module 0xc0ffee::m {
    fun test() {}
}
// second module

module 0xc0ffee::n {
    fun test() {}
}
```

This is not desirable (note that the second comment has now moved closer to first module).

**Comment by robinlzw** [comment]
fixed in https://github.com/movebit/movefmt/commit/c7e023c70d06876855f35930db1a0fcbd3880c6b
