### ISSUE TITLE
Wraps a portion of the fields

### ISSUE THREAD

**Issue by BriungRi** [movebit/movefmt#10]
In other formatters, I tend to see that formatters either keep a function invocation as a single line or break it up every argument into its own line. Feels strange to see it break a function invocation on wherever the column width limit is

**Comment by robinlzw** [comment]
This is a matter of personal preference, as different programmers have different views. Some developers prefer to wrap lines after exceeding the line width, for example, having 3 parameters in the first line and 2 parameters in the second line. This approach saves the number of lines in the source code. We will make adjustments in the next version to meet your expectations, only allowing function call statements to either be on a single line or have each parameter on its own line in a multi-line style.

**Comment by robinlzw** [comment]
fixed at https://github.com/movebit/movefmt/commit/2223c0d4ec6b65d9b23787dcf2d5b8e80ef70227
