### ISSUE TITLE
Keeps trailing commas for single lines

### ISSUE THREAD

**Issue by BriungRi** [movebit/movefmt#11]
This is mostly opinionated, because I think it looks ugly to keep a trailing comma when everything is in one line.

IMO, I really like keeping trailing commas when arguments are multi-line, because it means that I can add a new argument to the function/array without having to add a comma to the last argument

![Screenshot 2024-06-10 at 9 12 52 AM](https://github.com/movebit/movefmt/assets/8957844/bef3d580-8702-4c8d-8080-5510630e67c5)

**Comment by robinlzw** [comment]
We will optimize this area, thank you for your discovery.

**Comment by robinlzw** [comment]
fixed at https://github.com/movebit/movefmt/commit/95cd461309968a3c759fc59c67d2aa5dd999a454
