### ISSUE TITLE
Optimize the formatting logic of complex expression

### ISSUE THREAD

**Issue by robinlzw** [movebit/movefmt#17]
<img width="1003" alt="image" src="https://github.com/movebit/movefmt/assets/26412089/dae19822-f9a0-432d-bfc8-091f1dabaf67">

<img width="1040" alt="image" src="https://github.com/movebit/movefmt/assets/26412089/18770ff5-1cb5-4fca-946d-894ef67464c7">

**Comment by qpzmV** [comment]
fixed at https://github.com/movebit/movefmt/commit/ca29595713e54d0635bac3a3eb4add2277d83fa9
