### ISSUE TITLE
When formatter is run on move code with parse errors, it panics

### ISSUE THREAD

**Issue by vineethk** [movebit/movefmt#2]
Consider the following move code, which has a parse error:

```
module 0xc0ffee::m {
    fun foo() {
        assert!foo();
    }
}
```

Running the `movefmt` tool causes it to panic. Instead, we should get a user-friendly error message.

**Comment by robinlzw** [comment]
fixed in https://github.com/movebit/movefmt/commit/b1ad3f0ff7874c457195be5db0493c0dc481c9a5
