### ISSUE TITLE
Unnecessary and out-of-style space added after function name

### ISSUE THREAD

**Issue by vineethk** [movebit/movefmt#26]
This is on the `fea/optimize_240801` as well as the latest `develop` branch.

This code:

```
module 0xc0ffee::m {
    inline fun apply(f: |u8|bool, x: u8): bool {
        f(x)
    }
}
```

gets formatted to:

```
module 0xc0ffee::m {
    inline fun apply (f: |u8| bool, x: u8): bool {
        f(x)
    }
}
```

Note the space added after `apply` by the formatter.

**Comment by robinlzw** [comment]
Yeah, it's a bug; `apply` be considered as keyword

**Comment by robinlzw** [comment]
fixed at https://github.com/movebit/movefmt/commit/bc4e888b4cd281d08aca21692a81c74d8c4f9d44; and you can see more effects through this link https://github.com/movebit/aptos_move_dataset/commit/aa1a38a1815374bdcf3620b6237a46d731555f47
