### ISSUE TITLE
#[fmt::skip] does not work when applied to a module

### ISSUE THREAD

**Issue by vineethk** [movebit/movefmt#27]
Consider the following code:
```
#[fmt::skip]
module 0xc0ffee::m {
    public fun test() {
        if ({let x = foo(); !x}) {
            bar();
        }
    }
}
```

We would expect that this code would not be formatted by `movefmt`, because the `fmt::skip` applies to the entire module. However, `movefmt` only seems to respect attributes at the function level, but not at the module level, which it should.

**Comment by robinlzw** [comment]
fixed at https://github.com/movebit/movefmt/commit/fb07fa41b5e59ff3d4f75f146af38c262ff22e03; and you can see more effects through this link https://github.com/movebit/aptos_move_dataset/commit/1a43370a82e04ffa310059e10ee401721251da40
