### ISSUE TITLE
Move 2 support

### ISSUE THREAD

**Issue by magnum6actual** [movebit/movefmt#38]
If a module has any Move 2 code, it won't compile and therefore won't format.

**Comment by magnum6actual** [comment]
So it seems Move 2 support is in 1.0.5  Installing via Aptos CLI 4.2.1 installs movefmt 1.0.4 however.

**Comment by rahxephon89** [comment]
> So it seems Move 2 support is in 1.0.5 Installing via Aptos CLI 4.2.1 installs movefmt 1.0.4 however.

Hi @magnum6actual, you could use `aptos update movefmt --target-version 1.0.5` to upgrade to a new version.
