### ISSUE TITLE
[Bug] movefmt on the develop branch cannot parse randomness.move

### ISSUE THREAD

**Issue by rahxephon89** [movebit/movefmt#4]
When using the command `movefmt randomness.move` in `aptos-move/framework/aptos-framework/sources`, the error "2024-04-23T16:05:55.838676Z ERROR movefmt: file '"aptos-move/framework/aptos-framework/sources/randomness.move"' skipped because of parse not ok" is raised.

The movefmt binary is installed using the command `cargo install --git https://github.com/movebit/movefmt --branch develop movefmt`

**Comment by robinlzw** [comment]
fixed at develop branch.
