### ISSUE TITLE
`movefmt -q` does nothing

### ISSUE THREAD

**Issue by mkurnikov** [movebit/movefmt#44]
# 🐛 Bug

I'm trying to integrate the IDE with Movefmt. I need to receive updated file from stdout. 
I'm calling
```
movefmt --emit stdout -q FILE
```
and expect it to only return the updated file text. 

Doesn't work now, instead it returns 
```
2024-11-12T14:02:03.983809Z  WARN movefmt: 
            Currently movefmt is still in the beta testing phase.
            The formatting results of the beta version may be incompatible with the official release version.
        
options = GetOptsOptions { quiet: true, verbose: false, config_path: None, emit_mode: Some(Stdout), inline_config: {} }
module 0x1::modules {
    enum S {
        Inner(u8, u8)
    }
}

1 files successfully formatted
```

**Comment by robinlzw** [comment]
can you provide some screenshot?

**Comment by mkurnikov** [comment]
![image](https://github.com/user-attachments/assets/740627a0-85a3-4213-beb4-14c1e46e310d)

**Comment by robinlzw** [comment]
I've tested it locally and it works fine. The screenshot you provided indicates that the input file is quite simple, which results in the output of the stdout being identical to the input.

**Comment by mkurnikov** [comment]
I'm sorry, I don't understand what you're saying. 

It's not about the code formatting. I'm trying to consume the output of the movefmt stdout in my IDE, and then apply it to the in-memory file. For that, I need to have the new file source text, which is correctly presented if I provide `--emit stdout`. 

But right now, with `-q` ignored, so I need to filter out the irrelevant parts manually, which is error-prone. 

I've looked into your `develop` branch, `Verbosity::Quiet` enum variant isn't used anywhere. So, according to the codebase, `--quiet` option is completely ignored. 

Anyway, I indeed can disable logging, `options =` line goes to stderr, so the only thing to filter out is `N files successfully formatted` line, which always at the end, so it's easy to remove. 

![image](https://github.com/user-attachments/assets/c33091a6-fdb3-4cc3-a629-58fe16afe3bb)

**Comment by robinlzw** [comment]
I understand what you mean. You mean that "-q" does not output any information unrelated to the move code, right? We previously agreed that the meaning of "-q" is to not output DEBUG logs.

**Comment by mkurnikov** [comment]
Yes, i thought the -q is supposed to be a magical flag to hide all the output except for the file output. And if --emit has a different value, it hides everything.

**Comment by robinlzw** [comment]
If you need us to cooperate and modify the meaning of the -q option, you can reopen the issue, and we will fix this problem in the next version. Alternatively, you can use regular expressions to extract the content of the output file.

**Comment by mkurnikov** [comment]
Please, hide the "N files successfully formatted" if the `-q` option is passed.

**Comment by hapeeeeee** [comment]
We have fixed this in https://github.com/movebit/movefmt/commit/f4df9fefd8f9916ef968ba4ab04c4353ab44a971

<img width="818" alt="image" src="https://github.com/user-attachments/assets/ce4f7570-bf3a-4157-bede-135a68af39d3" />
<img width="849" alt="image" src="https://github.com/user-attachments/assets/9472def3-1b93-4535-96ed-11db4e71e45d" />
