### ISSUE TITLE
Cannot parse my chess.move code

### ISSUE THREAD

**Issue by banool** [movebit/movefmt#5]
This code compiles: https://github.com/banool/aptos-chess/blob/main/move/sources/chess.move.

But when you try to run the formatter, it fails:
```
options = GetOptsOptions { quiet: false, verbose: false, config_path: None, emit_mode: None, inline_config: {} }
2024-04-23T18:05:23.166769Z ERROR movefmt: file '"/Users/dport/github/aptos-chess/move/sources/chess.move"' skipped because of parse not ok
```

I just installed like this:
```
cargo install --git https://github.com/movebit/movefmt --branch develop movefmt
```

**Comment by robinlzw** [comment]
We will investigate this issue

**Comment by robinlzw** [comment]
Fixed it by https://github.com/movebit/movefmt/commit/f0388f1886508c587490f9064c03a31c5de6f4d0. The latest code is in the develop branch, and here is the changelog：
https://github.com/movebit/movefmt/blob/develop/doc/ChangeLog.md
