### ISSUE TITLE
Support running movefmt without a target file

### ISSUE THREAD

**Issue by banool** [movebit/movefmt#6]
It'd be nice if the tool worked like `cargo fmt`, where it just runs on everything by default.

**Comment by robinlzw** [comment]
Yeah, this is a great idea and we will implement it

**Comment by robinlzw** [comment]
We inplemented at https://github.com/movebit/movefmt/commit/b47544111b2ca4dfd014c2cc012bcc72a1963ec2

just run movefmt like this:
```
% movefmt
```

**Comment by robinlzw** [comment]
We can now format all the move files under the entire aptos-core repo, as shown in the screenshot.
<img width="1225" alt="image" src="https://github.com/movebit/movefmt/assets/26412089/338e2175-b0d6-4335-8d29-b988a1317b6e">
