### ISSUE TITLE
Long lines for pragmas

### ISSUE THREAD

**Issue by BriungRi** [movebit/movefmt#9]
![Screenshot 2024-06-10 at 9 10 49 AM](https://github.com/movebit/movefmt/assets/8957844/0edf610e-4690-4ec0-bf73-9f12962e8cbd)

**Comment by robinlzw** [comment]
This issue is not easy to resolve in the short term, and it is a known problem. Given its low occurrence rate, we plan to address it after two more releases

**Comment by robinlzw** [comment]
We added todo case at https://github.com/movebit/movefmt/tree/develop/tests/todo

**Comment by robinlzw** [comment]
fixed at https://github.com/movebit/movefmt/commit/aa0f86101965a21ba7dcdfccc0e4d6ca02974f87
